import { readFileSync, writeFileSync } from "node:fs";

const pilot = JSON.parse(
  readFileSync(new URL("../src/data/pilot.json", import.meta.url), "utf8"),
);
const quote = (value) => "'" + String(value).replaceAll("'", "''") + "'";
const values = pilot
  .map(
    (row, index) =>
      `(${index + 1}, ${quote(row.slug)}, ${quote(row.name)}, ${row.latitude}, ${row.longitude}, ${row.verified}, ${row.daysAgo}, ${row.offset}, ${row.sessions})`,
  )
  .join(",\n    ");
const sql = `-- Generated by npm run db:seed:generate from src/data/pilot.json.
-- LOCAL/DEVELOPMENT ONLY: these are fictional mosques and fictional schedules.
-- Run against a freshly migrated local database (supabase db reset).
do $$
declare
  item record;
  mosque uuid;
  schedule uuid;
  pilot_date date := (now() at time zone 'Asia/Karachi')::date;
  period_start date := (date_trunc('month', pilot_date) - interval '1 month')::date;
  period_end date := (date_trunc('month', pilot_date) + interval '2 months' - interval '1 day')::date;
begin
  for item in select * from (values
    ${values}
  ) as v(n, slug, name, lat, lng, verified, days_ago, time_offset, session_count)
  loop
    mosque := ('00000000-0000-4000-8000-' || lpad(item.n::text, 12, '0'))::uuid;
    schedule := ('10000000-0000-4000-8000-' || lpad(item.n::text, 12, '0'))::uuid;
    insert into public.mosques(id, slug, name, address_line, locality, city, country_code, latitude, longitude, timezone, verification_status, verified_at, is_synthetic)
    values(mosque, item.slug, item.name, item.n || ' Example Lane', 'Synthetic pilot', 'Karachi', 'PK', item.lat, item.lng, 'Asia/Karachi', case when item.verified then 'verified' else 'unverified' end, case when item.verified then now() else null end, true);
    insert into public.jamaat_schedules(id, mosque_id, effective_from, effective_to, status, published_at)
    values(schedule, mosque, period_start, period_end, 'published', ((pilot_date - item.days_ago)::timestamp at time zone 'Asia/Karachi'));
    insert into public.jamaat_schedule_entries(schedule_id, prayer, local_time)
    select schedule, prayer, clock + make_interval(mins => item.time_offset) from (values ('fajr', time '05:25'), ('dhuhr', time '13:15'), ('asr', time '17:15'), ('maghrib', time '18:45'), ('isha', time '20:30')) p(prayer, clock);
    insert into public.jumuah_sessions(schedule_id, position, local_time)
    select schedule, n, time '13:15' + make_interval(mins => (n - 1) * 45) from generate_series(1, item.session_count) n;
    insert into public.mosque_qr_codes(mosque_id) values(mosque);
    if item.n = 1 then
      insert into public.schedule_overrides(schedule_id, local_date, prayer, local_time) values(schedule, pilot_date + 1, 'isha', time '20:45');
    end if;
  end loop;
end;
$$;
`;
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
